In [2]:
import pandas as pd

df = pd.read_excel("../data/Professional_Retail_Sales_Dataset.xlsx")

In [3]:
df.head()

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Segment,City,State,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Payment Mode
0,ORD100002,2023-11-28,2023-11-30,CUST0203,Diya Shah,Home Office,Mumbai,Maharashtra,West,Furniture,Bookcase,Wooden Bookcase,9106.07,1,0.05,865.08,UPI
1,ORD100003,2023-03-30,2023-04-03,CUST0215,Rohan Gupta,Consumer,Chennai,Tamil Nadu,South,Furniture,Chair,Office Chair,1325.64,10,0.05,125.94,Net Banking
2,ORD100004,2023-03-05,2023-03-10,CUST0300,Yash Patel,Consumer,Ahmedabad,Gujarat,West,Office Supplies,Binder,Ring Binder,4249.48,5,0.20,84.99,UPI
3,ORD100005,2024-08-07,2024-08-10,CUST0287,Anaya Shah,Home Office,Kolkata,West Bengal,East,Office Supplies,Binder,Ring Binder,1064.56,6,0.30,-31.94,UPI
4,ORD100006,2024-07-31,2024-08-01,CUST0317,Kabir Verma,Home Office,Chennai,Tamil Nadu,South,Furniture,Table,Study Table,5897.06,8,0.15,265.37,Debit Card

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10000 non-null  str
 1   Order Date     10000 non-null  str
 2   Ship Date      10000 non-null  str
 3   Customer ID    10000 non-null  str
 4   Customer Name  10000 non-null  str
 5   Segment        10000 non-null  str
 6   City           10000 non-null  str
 7   State          10000 non-null  str
 8   Region         10000 non-null  str
 9   Category       10000 non-null  str
 10  Sub-Category   10000 non-null  str
 11  Product Name   10000 non-null  str
 12  Sales          10000 non-null  float64
 13  Quantity       10000 non-null  int64
 14  Discount       10000 non-null  float64
 15  Profit         10000 non-null  float64
 16  Payment Mode   10000 non-null  str
dtypes: float64(3), int64(1), str(13)
memory usage: 1.3 MB

In [5]:
df.describe()

              Sales      Quantity      Discount        Profit
count  10000.000000  10000.000000  10000.000000  10000.000000
mean    5022.884186      5.530400      0.134385    267.256626
std     2853.383121      2.862603      0.098790    321.658913
min      102.100000      1.000000      0.000000   -299.750000
25%     2533.127500      3.000000      0.050000     50.947500
50%     4991.990000      6.000000      0.150000    191.905000
75%     7477.505000      8.000000      0.200000    449.932500
max     9999.800000     10.000000      0.300000   1199.300000

In [6]:
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Customer ID      0
Customer Name    0
Segment          0
City             0
State            0
Region           0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Payment Mode     0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["Sales"].sum()

np.float64(50228841.86)

In [9]:
df["Profit"].sum()

np.float64(2672566.26)

In [10]:
df["Order ID"].nunique()

10000

In [11]:
df.groupby("City")["Sales"].sum().sort_values(ascending=False).head()

City
Lucknow      4419760.13
Mumbai       4402819.13
Hyderabad    4393555.65
Kolkata      4326507.86
Ahmedabad    4313057.58
Name: Sales, dtype: float64

In [12]:
df.groupby("Category")["Sales"].sum()

Category
Furniture          16740856.81
Office Supplies    16889782.74
Technology         16598202.31
Name: Sales, dtype: float64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10000 non-null  str
 1   Order Date     10000 non-null  str
 2   Ship Date      10000 non-null  str
 3   Customer ID    10000 non-null  str
 4   Customer Name  10000 non-null  str
 5   Segment        10000 non-null  str
 6   City           10000 non-null  str
 7   State          10000 non-null  str
 8   Region         10000 non-null  str
 9   Category       10000 non-null  str
 10  Sub-Category   10000 non-null  str
 11  Product Name   10000 non-null  str
 12  Sales          10000 non-null  float64
 13  Quantity       10000 non-null  int64
 14  Discount       10000 non-null  float64
 15  Profit         10000 non-null  float64
 16  Payment Mode   10000 non-null  str
dtypes: float64(3), int64(1), str(13)
memory usage: 1.3 MB

In [14]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10000 non-null  str
 1   Order Date     10000 non-null  datetime64[us]
 2   Ship Date      10000 non-null  datetime64[us]
 3   Customer ID    10000 non-null  str
 4   Customer Name  10000 non-null  str
 5   Segment        10000 non-null  str
 6   City           10000 non-null  str
 7   State          10000 non-null  str
 8   Region         10000 non-null  str
 9   Category       10000 non-null  str
 10  Sub-Category   10000 non-null  str
 11  Product Name   10000 non-null  str
 12  Sales          10000 non-null  float64
 13  Quantity       10000 non-null  int64
 14  Discount       10000 non-null  float64
 15  Profit         10000 non-null  float64
 16  Payment Mode   10000 non-null  str
dtypes: datetime64[us](2), float64(3), int64(1), str(11)
memory usage: 1.3 MB

In [16]:
df.describe()

,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2023-12-30 23:43:35.040000,2024-01-03 11:44:26.880000,5022.884186,5.530400,0.134385,267.256626
min,2023-01-01 00:00:00,2023-01-02 00:00:00,102.100000,1.000000,0.000000,-299.750000
25%,2023-07-04 00:00:00,2023-07-07 18:00:00,2533.127500,3.000000,0.050000,50.947500
50%,2024-01-01 00:00:00,2024-01-05 00:00:00,4991.990000,6.000000,0.150000,191.905000
75%,2024-06-28 00:00:00,2024-07-02 00:00:00,7477.505000,8.000000,0.200000,449.932500
max,2024-12-31 00:00:00,2025-01-06 00:00:00,9999.800000,10.000000,0.300000,1199.300000
std,NaN,NaN,2853.383121,2.862603,0.098790,321.658913

In [17]:
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Customer ID      0
Customer Name    0
Segment          0
City             0
State            0
Region           0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Payment Mode     0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
df["Month"] = df["Order Date"].dt.month_name()

In [21]:
df["Year"] = df["Order Date"].dt.year

In [22]:
df["Day"] = df["Order Date"].dt.day_name()

In [23]:
df["Profit Margin"] = (df["Profit"] / df["Sales"]) * 100

In [24]:
df.head()

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Segment,City,State,Region,Category,...,Product Name,Sales,Quantity,Discount,Profit,Payment Mode,Month,Year,Day,Profit Margin
0,ORD100002,2023-11-28,2023-11-30,CUST0203,Diya Shah,Home Office,Mumbai,Maharashtra,West,Furniture,...,Wooden Bookcase,9106.07,1,0.05,865.08,UPI,November,2023,Tuesday,9.500037
1,ORD100003,2023-03-30,2023-04-03,CUST0215,Rohan Gupta,Consumer,Chennai,Tamil Nadu,South,Furniture,...,Office Chair,1325.64,10,0.05,125.94,Net Banking,March,2023,Thursday,9.500317
2,ORD100004,2023-03-05,2023-03-10,CUST0300,Yash Patel,Consumer,Ahmedabad,Gujarat,West,Office Supplies,...,Ring Binder,4249.48,5,0.20,84.99,UPI,March,2023,Sunday,2.000009
3,ORD100005,2024-08-07,2024-08-10,CUST0287,Anaya Shah,Home Office,Kolkata,West Bengal,East,Office Supplies,...,Ring Binder,1064.56,6,0.30,-31.94,UPI,August,2024,Wednesday,-3.000301
4,ORD100006,2024-07-31,2024-08-01,CUST0317,Kabir Verma,Home Office,Chennai,Tamil Nadu,South,Furniture,...,Study Table,5897.06,8,0.15,265.37,Debit Card,July,2024,Wednesday,4.500039